export const PERSONAL = {
  name: 'Muhammad Ardiansyah',
  shortName: 'Ardi',
  initials: 'MA',
  role: 'Software Engineering Student (SMK)',
  tagline: "I'm a student building real products, not just school projects.",
  description: 'Vocational High School (SMK) student majoring in Software Engineering, seeking a PKL placement to apply my full-stack web & mobile skills in a real engineering team.',
  email: 'ardianssyahhh@gmail.com',
  github: 'https://github.com/Ardiansyahii',
  linkedin: 'https://www.linkedin.com/in/muhammad-ardiansyah-dev/',
  githubHandle: 'Ardiansyahii',
  linkedinHandle: 'muhammad-ardiansyah-dev',
  badge: 'Seeking PKL Placement',
  status: 'Available for PKL',
  year: new Date().getFullYear(),
  location: 'Indonesia 🇮🇩',
  timezone: 'WIB (UTC+7)',
  school: 'SMK Taruna Bhakti Depok',
  graduationYear: '2027',
}

export const TYPED_ROLES = [
  'Full-Stack Developer',
  'Mobile App Developer',
  'REST API Designer',
  'UI/UX Enthusiast',
]

export const STATS = [
  { number: '2+',  label: 'Years of Learning',   detail: 'Since 2022' },
  { number: '10+', label: 'Projects Shipped',     detail: 'Web & Mobile' },
  { number: '5+',  label: 'Tech Stacks Mastered', detail: 'Always growing' },
  { number: '∞',   label: 'Lines of Code',        detail: 'And counting...' },
]

export const NAV_LINKS = [
  { label: 'About',        href: '#about' },
  { label: 'Skills',       href: '#skills' },
  { label: 'Projects',    href: '#projects' },
  { label: 'Certificates', href: '#certificates' },
]

export const SKILL_CATEGORIES = [
  { key: 'all',      label: 'All' },
  { key: 'core',     label: 'Core' },
  { key: 'frontend', label: 'Frontend' },
  { key: 'backend',  label: 'Backend' },
  { key: 'mobile',   label: 'Mobile' },
  { key: 'database', label: 'Database' },
  { key: 'tools',    label: 'Tools' },
  { key: 'design',   label: 'Design' },
]

export const SKILLS = [
  { name: 'React.js',          cats: ['core','frontend'],           level: 90, color: '#61dafb' },
  { name: 'Next.js',           cats: ['core','frontend'],           level: 88, color: '#ffffff' },
  { name: 'Laravel',           cats: ['core','backend'],            level: 85, color: '#ff2d20' },
  { name: 'Expo React Native', cats: ['core','mobile'],             level: 82, color: '#000020' },
  { name: 'TypeScript',        cats: ['core','frontend','backend'], level: 80, color: '#3178c6' },
  { name: 'HTML5',             cats: ['frontend'],                  level: 95, color: '#e34f26' },
  { name: 'CSS3',              cats: ['frontend'],                  level: 90, color: '#1572b6' },
  { name: 'JavaScript',        cats: ['frontend'],                  level: 88, color: '#f7df1e' },
  { name: 'Tailwind CSS',      cats: ['frontend'],                  level: 92, color: '#38bdf8' },
  { name: 'Bootstrap',         cats: ['frontend'],                  level: 80, color: '#7952b3' },
  { name: 'Shadcn UI',         cats: ['frontend','design'],         level: 75, color: '#18181b' },
  { name: 'NextAuth.js',       cats: ['frontend'],                  level: 72, color: '#7c3aed' },
  { name: 'Zod',               cats: ['frontend','backend'],        level: 75, color: '#3068b7' },
  { name: 'Axios',             cats: ['frontend','backend'],        level: 85, color: '#5a29e4' },
  { name: 'Node.js',           cats: ['backend'],                   level: 82, color: '#339933' },
  { name: 'Express.js',        cats: ['backend'],                   level: 80, color: '#444444' },
  { name: 'PHP',               cats: ['backend'],                   level: 78, color: '#777bb4' },
  { name: 'Prisma ORM',        cats: ['backend','database'],        level: 78, color: '#2d3748' },
  { name: 'Google OAuth',      cats: ['backend'],                   level: 72, color: '#4285f4' },
  { name: 'Docker',            cats: ['backend','tools'],           level: 65, color: '#2496ed' },
  { name: 'Flutter',           cats: ['mobile'],                    level: 70, color: '#54c5f8' },
  { name: 'Dart',              cats: ['mobile'],                    level: 68, color: '#0175c2' },
  { name: 'MySQL',             cats: ['database'],                  level: 85, color: '#4479a1' },
  { name: 'PostgreSQL',        cats: ['database'],                  level: 80, color: '#336791' },
  { name: 'SQLite',            cats: ['database'],                  level: 75, color: '#003b57' },
  { name: 'Supabase',          cats: ['database'],                  level: 72, color: '#3ecf8e' },
  { name: 'Git',               cats: ['tools'],                     level: 90, color: '#f05032' },
  { name: 'GitHub',            cats: ['tools'],                     level: 88, color: '#24292e' },
  { name: 'GitLab',            cats: ['tools'],                     level: 75, color: '#fc6d26' },
  { name: 'Postman',           cats: ['tools'],                     level: 85, color: '#ff6c37' },
  { name: 'Trello',            cats: ['tools'],                     level: 80, color: '#0079bf' },
  { name: 'npm / pnpm',        cats: ['tools'],                     level: 85, color: '#cb3837' },
  { name: 'Figma',             cats: ['design'],                    level: 75, color: '#f24e1e' },
]

export const PROJECTS = [
  {
    id: 'sipmas',
    name: 'SIPMAS',
    subtitle: 'Sistem Informasi Pengaduan Masyarakat',
    category: 'Multi-Platform System',
    year: '2024',
    description: 'A multi-platform community complaint & reporting system for RT/RW-level governance — facilitating transparent communication between residents and administrators.',
    impact: 'Digitized manual complaint workflows for local government, reducing response time significantly.',
    features: [
      'Real-time complaint tracking & audit logs',
      'Web (Next.js) + Mobile (Expo React Native)',
      'REST API with Express.js & MySQL/Supabase',
      'Role-based access control with JWT',
    ],
    tags: ['Next.js', 'Expo RN', 'Express.js', 'MySQL', 'Supabase', 'TypeScript'],
    github: 'https://github.com/Ardiansyahii',
    live: null,
    accentColor: '#6366f1',
    number: '01',
  },
  {
    id: 'geniuslib',
    name: 'GeniusLib',
    subtitle: 'School Library Management System',
    category: 'Hybrid Application',
    year: '2024',
    description: 'A hybrid library system combining a web dashboard for librarians and an Android app for students — modernizing physical library circulation through digital tools.',
    impact: 'Eliminated paper-based borrowing records and introduced QR-based digital membership.',
    features: [
      'Online catalog (OPAC) with book reservation',
      'QR Code-based digital membership cards',
      'Automated fine calculation & return system',
      'Librarian web + Student mobile app',
    ],
    tags: ['Next.js', 'Expo RN', 'Express.js', 'MySQL', 'Tailwind CSS', 'QR Code'],
    github: 'https://github.com/Ardiansyahii',
    live: null,
    accentColor: '#22d3ee',
    number: '02',
  },
]

// ──────────────────────────────────────────────
// Certificates — from PDFs
// ──────────────────────────────────────────────
export const CERT_CATEGORIES = [
  { key: 'all',         label: 'All' },
  { key: 'featured',    label: 'Featured' },
  { key: 'frontend',    label: 'Frontend' },
  { key: 'backend',     label: 'Backend' },
  { key: 'programming', label: 'Programming' },
  { key: 'cloud',       label: 'Cloud & AI' },
  { key: 'ai',          label: 'AI' },
  { key: 'other',       label: 'Other' },
]

export const CERTIFICATES = [
  {
    id: 'dbs-coding-camp',
    name: 'Coding Camp 2026 — Full-Stack Web Developer',
    issuer: 'DBS Foundation × Dicoding',
    issuerShort: 'DBS Foundation',
    date: 'May 11, 2026',
    year: '2026',
    credentialId: 'CFS292D6Y529',
    verifyUrl: null,
    category: 'featured',
    highlight: true,
    description: 'Highly selective full-stack bootcamp (Jan–May 2026). Completed 10 courses + 250-hour capstone project. Full Graduate status.',
  },
  {
    id: 'react',
    name: 'Belajar Membuat Aplikasi Web dengan React',
    issuer: 'Dicoding Indonesia',
    issuerShort: 'Dicoding',
    date: '09 Feb 2026',
    year: '2026',
    credentialId: 'QLZ96JMMMZ5D',
    verifyUrl: 'https://www.dicoding.com/certificates/QLZ96JMMMZ5D',
    category: 'frontend',
    highlight: false,
  },
  {
    id: 'backend-js',
    name: 'Belajar Back-End Pemula dengan JavaScript',
    issuer: 'Dicoding Indonesia × AWS',
    issuerShort: 'Dicoding × AWS',
    date: '04 Feb 2026',
    year: '2026',
    credentialId: 'NVP7JMKVOXR0',
    verifyUrl: 'https://www.dicoding.com/certificates/NVP7JMKVOXR0',
    category: 'backend',
    highlight: false,
  },
  {
    id: 'frontend-web',
    name: 'Belajar Membuat Front-End Web untuk Pemula',
    issuer: 'Dicoding Indonesia',
    issuerShort: 'Dicoding',
    date: '02 Feb 2026',
    year: '2026',
    credentialId: '1RXYQ5KDQZVM',
    verifyUrl: 'https://www.dicoding.com/certificates/1RXYQ5KDQZVM',
    category: 'frontend',
    highlight: false,
  },
  {
    id: 'prompt-engineering',
    name: 'Prompt Engineering untuk Software Developer',
    issuer: 'Dicoding Indonesia × Google',
    issuerShort: 'Dicoding × Google',
    date: '01 Feb 2026',
    year: '2026',
    credentialId: 'ERZR2R672PYV',
    verifyUrl: 'https://www.dicoding.com/certificates/ERZR2R672PYV',
    category: 'ai',
    highlight: false,
  },
  {
    id: 'js-dasar',
    name: 'Belajar Dasar Pemrograman JavaScript',
    issuer: 'Dicoding Indonesia × AWS',
    issuerShort: 'Dicoding × AWS',
    date: '30 Jan 2026',
    year: '2026',
    credentialId: '6RPNGQ9O9Z2M',
    verifyUrl: 'https://www.dicoding.com/certificates/6RPNGQ9O9Z2M',
    category: 'programming',
    highlight: false,
  },
  {
    id: 'web-dasar',
    name: 'Belajar Dasar Pemrograman Web',
    issuer: 'Dicoding Indonesia × Google',
    issuerShort: 'Dicoding × Google',
    date: '20 Jan 2026',
    year: '2026',
    credentialId: 'RVZKG2VJQXD5',
    verifyUrl: 'https://www.dicoding.com/certificates/RVZKG2VJQXD5',
    category: 'frontend',
    highlight: false,
  },
  {
    id: 'aws-cloud',
    name: 'Belajar Dasar Cloud dan Gen AI di AWS',
    issuer: 'Dicoding Indonesia × AWS',
    issuerShort: 'Dicoding × AWS',
    date: '15 Jan 2026',
    year: '2026',
    credentialId: '1OP8JKWOLPQK',
    verifyUrl: 'https://www.dicoding.com/certificates/1OP8JKWOLPQK',
    category: 'cloud',
    highlight: false,
  },
  {
    id: 'programming-logic',
    name: 'Pengenalan ke Logika Pemrograman (Programming Logic 101)',
    issuer: 'Dicoding Indonesia',
    issuerShort: 'Dicoding',
    date: '11 Jan 2026',
    year: '2026',
    credentialId: '2VX35DR7JPYQ',
    verifyUrl: 'https://www.dicoding.com/certificates/2VX35DR7JPYQ',
    category: 'programming',
    highlight: false,
  },
  {
    id: 'software-dev-basics',
    name: 'Memulai Dasar Pemrograman untuk Menjadi Pengembang Software',
    issuer: 'Dicoding Indonesia × Prakerja',
    issuerShort: 'Dicoding × Prakerja',
    date: '11 Jan 2026',
    year: '2026',
    credentialId: 'MEPJ21N0WP3V',
    verifyUrl: 'https://www.dicoding.com/certificates/MEPJ21N0WP3V',
    category: 'programming',
    highlight: false,
  },
  {
    id: 'financial-literacy',
    name: 'Introduction to Financial Literacy',
    issuer: 'Dicoding Indonesia × DBS Foundation',
    issuerShort: 'Dicoding × DBS',
    date: '19 Des 2025',
    year: '2025',
    credentialId: '2VX35DG33PYQ',
    verifyUrl: 'https://www.dicoding.com/certificates/2VX35DG33PYQ',
    category: 'other',
    highlight: false,
  },
]
